// 기존 Material 이름 → @impact7/ui 아이콘 SSoT 브릿지.
import { ICON_SVGS } from '@impact7/ui/icons';

const MS_TO_SSOT = {
  add: 'plus',
  add_circle: 'plus-circle',
  admin_panel_settings: 'shieldCheck',
  analytics: 'presentation-chart',
  apartment: 'buildingOffice',
  apps: 'squares-four',
  archive: 'archive',
  arrow_back: 'arrowLeft',
  arrow_forward: 'arrowRight',
  assignment: 'clipboardDocument',
  assignment_ind: 'identification-card',
  assignment_late: 'warning-circle',
  auto_awesome: 'sparkles',
  auto_stories: 'book-open',
  bar_chart: 'chartBar',
  bolt: 'bolt',
  calendar_month: 'calendarDays',
  calendar_today: 'calendar',
  cancel: 'xCircle',
  category: 'squaresPlus',
  check: 'check',
  check_box: 'check-circle',
  check_box_outline_blank: 'circle',
  check_circle: 'check-circle',
  checklist: 'list-bullets',
  chevron_left: 'caret-left',
  chevron_right: 'caret-right',
  class: 'book-open',
  close: 'x',
  cloud_upload: 'cloud-arrow-up',
  contact_phone: 'phone',
  content_copy: 'copy',
  dark_mode: 'moon',
  database: 'circleStack',
  date_range: 'calendar-dots',
  delete: 'trash',
  delete_forever: 'trash',
  description: 'file-text',
  directions_walk: 'arrowLongRight',
  domain_verification: 'shieldCheck',
  download: 'download',
  edit: 'pencil',
  edit_calendar: 'calendar-dots',
  edit_note: 'pencilSquare',
  error: 'warning-circle',
  event: 'calendarDays',
  event_available: 'seal-check',
  event_busy: 'noSymbol',
  event_note: 'file-text',
  event_repeat: 'arrowPathRoundedSquare',
  event_upcoming: 'calendar-dots',
  expand_less: 'caret-up',
  expand_more: 'caret-down',
  explore: 'globeAlt',
  fact_check: 'seal-check',
  family_restroom: 'users',
  filter_alt: 'funnel',
  filter_list: 'funnel',
  folder_open: 'folder-open',
  format_list_numbered: 'numberedList',
  forum: 'chats',
  grading: 'clipboardDocumentCheck',
  grid_on: 'tableCells',
  group: 'users',
  groups: 'users-three',
  help: 'questionMarkCircle',
  history: 'clock',
  history_edu: 'graduation-cap',
  hotel: 'homeModern',
  how_to_reg: 'identification-card',
  image: 'photo',
  info: 'informationCircle',
  keep: 'bookmark',
  keep_off: 'bookmarkSlash',
  label: 'tag',
  link: 'link',
  location_city: 'buildings',
  login: 'arrowRightEndOnRectangle',
  logout: 'logout',
  mail: 'envelope',
  menu: 'list',
  menu_book: 'book-open',
  notifications: 'bell',
  pending_actions: 'dots-three-circle',
  people: 'users',
  person: 'user',
  person_add: 'user-plus',
  person_off: 'user-minus',
  person_remove: 'user-minus',
  person_search: 'magnifying-glass',
  phone_android: 'device-mobile',
  phone_callback: 'phoneArrowDownLeft',
  phone_in_talk: 'phone',
  play_circle: 'playCircle',
  print: 'printer',
  quiz: 'clipboard-text',
  radio_button_unchecked: 'circle',
  refresh: 'arrows-clockwise',
  save: 'arrowDownOnSquare',
  schedule: 'clock',
  school: 'graduation-cap',
  search: 'magnifying-glass',
  send: 'paper-plane-tilt',
  settings: 'cog',
  smart_toy: 'cpuChip',
  sms: 'chatBubbleLeftEllipsis',
  sticky_note_2: 'file-text',
  swap_horiz: 'arrows-left-right',
  table: 'tableCells',
  task_alt: 'check-circle',
  timeline: 'arrowTrendingUp',
  today: 'calendar',
  toggle_on: 'adjustmentsHorizontal',
  tune: 'adjustmentsHorizontal',
  undo: 'arrowUturnLeft',
  update: 'arrows-clockwise',
  upload: 'upload',
  upload_file: 'documentArrowUp',
  view_agenda: 'queueList',
  view_module: 'squares-four',
  warning: 'exclamationTriangle',
  insights: 'arrowTrendingUp',
  view_list: 'list-bullets',
  replay: 'arrows-clockwise',
  monitoring: 'presentation-chart',
  science: 'flask',
  pause_circle: 'pause-circle',

};

export function msIcon(name, extraClass = '', attrs = '') {
  const key = MS_TO_SSOT[name] || name;
  const body = ICON_SVGS[key];
  if (!body) {
    console.warn('[ms-icon] unmapped icon:', name);
    return '';
  }
  const cls = extraClass ? `i7-icon ${extraClass}` : 'i7-icon';
  // 아이콘 자체가 인터랙티브(role/tabindex/aria-label 부여)면 aria-hidden을 빼야 스크린리더가 읽는다
  const interactive = /(^|\s)(?:role=|aria-label=|tabindex=)/.test(attrs);
  const a11y = interactive ? '' : ' aria-hidden="true"';
  return `<svg class="${cls}" viewBox="0 0 256 256" width="1em" height="1em" fill="currentColor"${a11y}${attrs ? ' ' + attrs : ''}>${body}</svg>`;
}
