// Material Symbols → @impact7/ui 아이콘 SSoT 브릿지.
// 코드는 기존 material 이름을 그대로 쓰고, 렌더만 heroicons SVG로 나간다.
// class는 material-symbols-outlined 유지 — 기존 CSS 크기 규칙(font-size → 1em)이 그대로 적용된다.
import { ICON_PATHS } from '@impact7/ui/icons';

const MS_TO_SSOT = {
  add: 'plus',
  add_circle: 'plusCircle',
  admin_panel_settings: 'shieldCheck',
  analytics: 'presentationChartLine',
  apartment: 'buildingOffice',
  apps: 'squares2x2',
  archive: 'archiveBox',
  arrow_back: 'arrowLeft',
  arrow_forward: 'arrowRight',
  assignment: 'clipboardDocument',
  assignment_ind: 'identification',
  assignment_late: 'exclamationCircle',
  auto_awesome: 'sparkles',
  auto_stories: 'bookOpen',
  bar_chart: 'chartBar',
  bolt: 'bolt',
  calendar_month: 'calendarDays',
  calendar_today: 'calendar',
  cancel: 'xCircle',
  category: 'squaresPlus',
  check: 'check',
  check_box: 'checkCircle',
  check_box_outline_blank: 'circle',
  check_circle: 'checkCircle',
  checklist: 'listBullet',
  chevron_left: 'chevronLeft',
  chevron_right: 'chevronRight',
  class: 'bookOpen',
  close: 'xMark',
  cloud_upload: 'cloudArrowUp',
  contact_phone: 'phone',
  content_copy: 'documentDuplicate',
  dark_mode: 'moon',
  database: 'circleStack',
  date_range: 'calendarDateRange',
  delete: 'trash',
  delete_forever: 'trash',
  description: 'documentText',
  directions_walk: 'arrowLongRight',
  domain_verification: 'shieldCheck',
  download: 'download',
  edit: 'pencil',
  edit_calendar: 'calendarDateRange',
  edit_note: 'pencilSquare',
  error: 'exclamationCircle',
  event: 'calendarDays',
  event_available: 'checkBadge',
  event_busy: 'noSymbol',
  event_note: 'documentText',
  event_repeat: 'arrowPathRoundedSquare',
  event_upcoming: 'calendarDateRange',
  expand_less: 'chevronUp',
  expand_more: 'chevronDown',
  explore: 'globeAlt',
  fact_check: 'documentCheck',
  family_restroom: 'users',
  filter_alt: 'funnel',
  filter_list: 'funnel',
  folder_open: 'folderOpen',
  format_list_numbered: 'numberedList',
  forum: 'chatBubbleLeftRight',
  grading: 'clipboardDocumentCheck',
  grid_on: 'tableCells',
  group: 'users',
  groups: 'userGroup',
  help: 'questionMarkCircle',
  history: 'clock',
  history_edu: 'academicCap',
  hotel: 'homeModern',
  how_to_reg: 'identification',
  image: 'photo',
  info: 'informationCircle',
  keep: 'bookmark',
  keep_off: 'bookmarkSlash',
  label: 'tag',
  link: 'link',
  location_city: 'buildingOffice2',
  login: 'arrowRightEndOnRectangle',
  logout: 'logout',
  mail: 'envelope',
  menu: 'bars3',
  menu_book: 'bookOpen',
  notifications: 'bell',
  pending_actions: 'ellipsisHorizontalCircle',
  people: 'users',
  person: 'user',
  person_add: 'userPlus',
  person_off: 'userMinus',
  person_remove: 'userMinus',
  person_search: 'magnifyingGlassCircle',
  phone_android: 'devicePhoneMobile',
  phone_callback: 'phoneArrowDownLeft',
  phone_in_talk: 'phone',
  play_circle: 'playCircle',
  print: 'printer',
  quiz: 'clipboardDocumentList',
  radio_button_unchecked: 'circle',
  refresh: 'arrowPath',
  save: 'arrowDownOnSquare',
  schedule: 'clock',
  school: 'academicCap',
  search: 'magnifier',
  send: 'paperAirplane',
  settings: 'cog',
  smart_toy: 'cpuChip',
  sms: 'chatBubbleLeftEllipsis',
  sticky_note_2: 'documentText',
  swap_horiz: 'arrowsRightLeft',
  table: 'tableCells',
  task_alt: 'checkCircle',
  timeline: 'arrowTrendingUp',
  today: 'calendar',
  toggle_on: 'adjustmentsHorizontal',
  tune: 'adjustmentsHorizontal',
  undo: 'arrowUturnLeft',
  update: 'arrowPath',
  upload: 'upload',
  upload_file: 'documentArrowUp',
  view_agenda: 'queueList',
  view_module: 'squares2x2',
  warning: 'exclamationTriangle',
  insights: 'arrowTrendingUp',
  view_list: 'listBullet',
  replay: 'arrowPath',
  monitoring: 'presentationChartLine',
  science: 'beaker',
  pause_circle: 'pauseCircle',

};

export function msIcon(name, extraClass = '', attrs = '') {
  const key = MS_TO_SSOT[name] || name;
  const d = ICON_PATHS[key];
  if (!d) {
    console.warn('[ms-icon] unmapped icon:', name);
    return '';
  }
  const cls = extraClass ? `material-symbols-outlined ${extraClass}` : 'material-symbols-outlined';
  // 아이콘 자체가 인터랙티브(role/tabindex/aria-label 부여)면 aria-hidden을 빼야 스크린리더가 읽는다
  const interactive = /(^|\s)(?:role=|aria-label=|tabindex=)/.test(attrs);
  const a11y = interactive ? '' : ' aria-hidden="true"';
  return `<svg class="${cls}" viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"${a11y}${attrs ? ' ' + attrs : ''}><path d="${d}"/></svg>`;
}
