import {
  archive,
  arrowClockwise,
  arrowsClockwise,
  arrowsLeftRight,
  bellRinging,
  bookOpen,
  calendar,
  calendarDots,
  caretDown,
  caretLeft,
  caretRight,
  caretUp,
  chats,
  check,
  checkCircle,
  clipboardText,
  clock,
  deviceMobile,
  dotsThreeCircle,
  download,
  fileText,
  flask,
  gear,
  identificationCard,
  listBullets,
  magnifyingGlass,
  money,
  paperPlaneTilt,
  pauseCircle,
  pencil,
  phoneX,
  presentationChart,
  sealCheck,
  signOut,
  trash,
  upload,
  userMinus,
  usersThree,
  warningCircle,
  x,
} from '@impact7/ui/icons/named';

// dashboard·messages(React) 기존 이름 → @impact7/ui 아이콘 SVG body 매핑.
// tree-shakeable named import 기반, Icon/IconButton의 svg prop에 넣는다.
// 슬러그를 직접 쓰던 콜사이트를 위한 슬러그 키(kebab)도 함께 둔다.
export const ICON_SVG = {
  groups: usersThree,
  chevron_right: caretRight,
  chevron_left: caretLeft,
  view_list: listBullets,
  error: warningCircle,
  event_note: fileText,
  menu_book: bookOpen,
  replay: arrowsClockwise,
  download,
  forum: chats,
  pending_actions: dotsThreeCircle,
  quiz: clipboardText,
  today: calendar,
  monitoring: presentationChart,
  send: paperPlaneTilt,
  bulk_message: magnifyingGlass,
  direct_message: deviceMobile,
  notification_missing: bellRinging,
  message_history: chats,
  phone_opt_out: phoneX,
  upload,
  refresh: arrowsClockwise,
  payments: money,
  expand_less: caretUp,
  expand_more: caretDown,
  science: flask,
  how_to_reg: identificationCard,
  schedule: clock,
  person_off: userMinus,
  assignment_late: warningCircle,
  logout: signOut,
  pause_circle: pauseCircle,
  fact_check: sealCheck,
  event_available: sealCheck,

  // literal name/icon 콜사이트용 슬러그 키
  'calendar-dots': calendarDots,
  check,
  archive,
  trash,
  'arrow-clockwise': arrowClockwise,
  'arrows-left-right': arrowsLeftRight,
  x,
  pencil,
  'check-circle': checkCircle,
  gear,
};
