// dashboard·messages(React) 기존 이름 → @impact7/ui 공용 아이콘 키 매핑.
// 값은 Phosphor 슬러그(kebab). @impact7/ui가 Heroicons alias도 하위호환으로 노출하지만
// 에코시스템 Phosphor 전환에 맞춰 정식 슬러그를 SSoT로 쓴다.
export const ICON_NAME = {
  groups: 'users-three',
  chevron_right: 'caret-right',
  chevron_left: 'caret-left',
  view_list: 'list-bullets',
  error: 'warning-circle',
  event_note: 'file-text',
  menu_book: 'book-open',
  replay: 'arrows-clockwise',
  download: 'download',
  forum: 'chats',
  pending_actions: 'dots-three-circle',
  quiz: 'clipboard-text',
  today: 'calendar',
  monitoring: 'presentation-chart',
  send: 'paper-plane-tilt',
  bulk_message: 'magnifying-glass',
  direct_message: 'device-mobile',
  notification_missing: 'bell-ringing',
  message_history: 'chats',
  phone_opt_out: 'phone-x',
  upload: 'upload',
  refresh: 'arrows-clockwise',
  payments: 'money',
  expand_less: 'caret-up',
  expand_more: 'caret-down',
  science: 'flask',
  how_to_reg: 'identification-card',
  schedule: 'clock',
  person_off: 'user-minus',
  assignment_late: 'warning-circle',
  logout: 'sign-out',
  pause_circle: 'pause-circle',
  fact_check: 'seal-check',
  event_available: 'seal-check',
};
